### ISSUE TITLE
Why it doesn't work in Unity2017?

### ISSUE THREAD

**Issue by handsomesnail** [Zhuangdum/RadarChart#1]
MissingComponentException: There is no 'RectTransform' attached to the "Missing Prefab (Dummy)" game object, but a script is trying to access it.
You probably need to add a RectTransform to the game object "Missing Prefab (Dummy)". Or your script needs to check if the component is attached before using it.
Maybe something missed

**Comment by Zhuangdum** [comment]
thank you for you suggestions, i have added components required already, and fix the null reference exception.
